### ISSUE TITLE
mutex 2.0.0-SNAPSHOT BUILD FAILURE

### ISSUE THREAD

**Issue by XiangweiZhai** [PathwayAndDataAnalysis/mutex#10]
Could not resolve dependencies for project org.cbio:mutex:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at “org.panda:utility:jar:1.2.0-SNAPSHOT”.
I checked the pom.xml and found that 4 dependencies are required to compile mutex：utility，resource(org.panda), junit and commons-math3.
When I run the code, the following error will be reported：
**warning**: Could not transfer metadata org.panda:**utility or resource**:1.2.0-SNAPSHOT/maven-metadata.xml from/to panda.
The reason may be that **utility or resource** cannot be downloaded from the "https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/" provided by the pom.xml.
This seems to be an inaccessible website. Should I change to another mirror website that can provide downloads?

**Comment by ozgunbabur** [comment]
Hi @XiangweiZhai,

I cannot duplicate this error. I tried downloading and compiling the code on a fresh virtual Ubuntu system, and it worked without any problems. I simply followed the instructions on the front page. 

The "https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/" link does not work if you click on it in a browser, but it works in Maven. That's probably because Maven doesn't browse the folders, but directly requests files such as this one "https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/org/panda/utility/1.2.0-SNAPSHOT/maven-metadata.xml", which works.

Can you please provide more information about your environment? And what exactly are you doing to get this error?

**Comment by XiangweiZhai** [comment]
HI ozgunbabur,
Thank you very much for your guidance！I run the project on the server.
Operating system：Ubuntu 16.04 LTS
Operating environment：java 1.8.0_275  Apache Maven 3.6.3
I followed the instructions on the front page to run the program and the same error occurred.
first step : I used Git to download the code successfully 
`zhaixw@master:~$ git clone https://github.com/PathwayAndDataAnalysis/mutex`

second step：The error appeared when I compiled the project.
`zhaixw@master:~$ cd mutex/`
`zhaixw@master:~/mutex$ ls`
`pom.xml  README.md  src`
`zhaixw@master:~/mutex$ /home/zhaixw/maven/apache-maven-3.6.3/bin/mvn clean  compile`

REEOR:
`[ERROR] Failed to execute goal on project mutex: Could not resolve dependencies for project org.cbio:mutex:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at org.panda:utility:jar:1.2.0-SNAPSHOT: Failed to read artifact descriptor for org.panda:utility:jar:1.2.0-SNAPSHOT: Could not transfer artifact org.panda:utility:pom:1.2.0-SNAPSHOT from/to panda (https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/): Transfer failed for https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/org/panda/utility/1.2.0-SNAPSHOT/utility-1.2.0-SNAPSHOT.pom: Connect to raw.githubusercontent.com:443 [raw.githubusercontent.com/0.0.0.0, raw.githubusercontent.com/0:0:0:0:0:0:0:0] failed: Connection refused (Connection refused)`
I have no idea about this, would you mind giving me more advice？Thank you very much!

**Comment by ozgunbabur** [comment]
@XiangweiZhai, thanks for the detailed description. But I cannot duplicate it. I just tried to download and compile Mutex on another Fresh Ubuntu 20.04.1 LTS, with Maven 3.6.3 and Oracle JDK 15.0.1. It worked without any problems. 

What you are getting is a "Connection refused" error. Could it be the server is refusing requests from you but accepting mine? Which part of the world are you located in? I am in the USA. 

Do you want me to generate a jar with the latest code and send you?

**Comment by XiangweiZhai** [comment]
HI ozgunbabur,
I am in Shenzhen ,China. I used a server located in the United States and the project was compiled successfully! Thank you!
But there were still few warnings：
`[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!`
`[WARNING] /root/mutex/src/main/java/org/cbio/mutex/Group.java: Some input files use unchecked or unsafe operations.`
`[WARNING] /root/mutex/src/main/java/org/cbio/mutex/Group.java: Recompile with -Xlint:unchecked for details.`
These warnings do not seem to affect the operation of the project，right？

**Comment by ozgunbabur** [comment]
I am glad there is a way around it, and I am surprised that GitHub is blocking China. 

Those warnings haven't caused any problem yet. I frequently used the code in Ubuntu. 

Please let me know how it goes with Mutex.
