### ISSUE TITLE
java.lang.NullPointerException error

### ISSUE THREAD

**Issue by blueskypie** [PathwayAndDataAnalysis/mutex#11]
I followed the instruction to download the code by `git clone https://github.com/PathwayAndDataAnalysis/mutex` and compile and built the jar successfully, but when I run the code, I got this error:

```
$ ls /home/jack/beti.corr/mutex
mut.mutex.tab  parameters.txt

$ more /home/jack/beti.corr/mutex/parameters.txt
data-file = mut.mutex.tab

$ java -jar target/mutex.jar /home/jack/beti.corr/mutex
Exception in thread "main" java.lang.NullPointerException
        at org.cbio.mutex.Main.main(Main.java:124)
```

some warnings I got during the compiling

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

warnings I got during the building
> [WARNING] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.
Instead of attaching the assembly file: /mnt/data01/n/home/jike.cui/tool/mutex/target/mutex.jar, it will become the file for main project artifact.

**Comment by ozgunbabur** [comment]
Hi @blueskypie, 

I just tracked down the error. Previously the default value of the search-on-signaling-network parameter was true. In your case, the error was the lack of the network file. I changed the default to false. It should work now. Please update and try again.

**Comment by blueskypie** [comment]
Thanks, it's working now!
