### ISSUE TITLE
network file not generated

### ISSUE THREAD

**Issue by john-alexander** [PathwayAndDataAnalysis/mutex#13]
Hiya,

I've managed to run mutex  using the following commnad
```
java -jar target/mutex.jar path/to/data

parameters.txt contains
data-file=datafile.txt
network-file=netowkfile```
```
I seem to get a ranked-group.txt output although there is no network file provided.I noticed this in the README regarding .sif file but cant seem to access it
```
Add PC.sif
For some reason tt looks like Google is limiting access to large files in googlecode repositories. 
Please download this file from http://cbio.mskcc.org/~ozgun/PC.sif.gz, and extract the file PC.sif into the working directory 
(same folder of `mutex.jar`).
```
The link is inaccessible. Please can you suggest a solution.
Best,
John

**Comment by ozgunbabur** [comment]
Hi John,

Please find the latest version of this file at
https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.Detailed.hgnc.sif.gz

Best,
Ozgun

**Comment by john-alexander** [comment]
Hi Ozgun

Thank you for the response.  I tried to run mutex again renaming the downloaded file to PC.sif - doesn't look like a PC/ was generated. Is the network file generated by default or is a specific parameter required? 
Please let me know if I'm missing something.

Kind regards,

John

**Comment by john-alexander** [comment]
Hi Ozgun,

Would you be able to help with the above?

**Comment by ozgunbabur** [comment]
Hi John,

Sorry for not getting back to you earlier. I was very distracted by some work. 
Is it possible for you to attach your input files here so that I can go over and see what is happening?

**Comment by john-alexander** [comment]
Hi Ozgun,

No problem, cheers for getting back.  Attaching input and param file here :
[Matrix_CNA_RNA__Table1__mutex_input.txt](https://github.com/PathwayAndDataAnalysis/mutex/files/9607494/Matrix_CNA_RNA__Table1__mutex_input.txt)
[parameters.txt](https://github.com/PathwayAndDataAnalysis/mutex/files/9607498/parameters.txt)

Kind regards,

John

**Comment by ozgunbabur** [comment]
Hi John,

You can run Mutex without providing a network file. Please remove the line

```network-file = Matrix_CNA_RNA__Table1__mutex_network.txt```

from your parameters. The software has a default network that is derived from Pathway Commons, SPIKE, and SignaLink databases. So when you use the parameter

```search-on-signaling-network = true```

but not provide any network, it will use that default network. But also, you don't have to use any network for Mutex. You can say

```search-on-signaling-network = false```

and Mutex will run as if everything can be connected. 

The first configuration does not produce any results on your dataset. The second one does, but the scores don't look highly significant (some are borderline).

**Comment by john-alexander** [comment]
Hi Ozgun,

I did get an output with the 2nd configuration but it doesn't produce a merged-network.sif output file for me. Is this expected with this configuration?

Im testing this with ~5000 genes now (attached input) - but it looks like it would take a while to complete.
[Matrix_CNA_RNA__all_genes__mutex1.txt](https://github.com/PathwayAndDataAnalysis/mutex/files/9615873/Matrix_CNA_RNA__all_genes__mutex1.txt)


Best,

J

**Comment by john-alexander** [comment]
java -jar target/mutex.jar .

Directory = ./
Number of genes = 5434
Number of samples = 76

 Btw I ran the above and it finished in 25 hours - also did not produce a .sif output 

Time elapsed: 25h, 53m, 5s

**Comment by ozgunbabur** [comment]
It is good that we got it running! There are several things:

1. A network result is only generated if a network is used in the analysis (configuration 1) **and** an FDR cutoff or a score cutoff is provided. An FDR cutoff requires the null distribution of scores to be computed and that requires a cluster with many cores. The easier option is to use a score cutoff. For instance, you can use the parameter

```score-cutoff = 0.02```

2. To reduce noise, to cut down multiple hypothesis testing, and to speed up the execution, we can filter out genes with a few alterations using 

```minimum-alteration-count-threshold = 3```

3. Please update the project with ```git pull``` and regenerate the jar file as described on the GitHub front page. There was some incompatibility with a recent change in one of the libraries. You should be able to use the default network after the update.

**Comment by john-alexander** [comment]
Thank you - All seems to be OK in the installation except for 
```
[WARNING] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.

```
I can confirm that it generates a .sif file now - testing this on the small input file (which contains 220 genes). For some reason takes on 83 genes though

Directory = ./
Number of genes = 83
Number of samples = 76

I now have the follow output
```
ranked-groups.txt
merged-network.sif
result-groups.cus
merged-network.format
co-occurred.sif
co-occurred.format
oncoprint.txt

```

**Comment by ozgunbabur** [comment]
That's great. Is there anything in the SIF files or are they just empty?

**Comment by john-alexander** [comment]
I was just installing ChiBE to see if I can load this. 

They have an output :-) !!

```
 cat merged-network.sif 
POLD4	controls-state-change-of	NBN
NBN	controls-state-change-of	TP53
TP53	controls-expression-of	NBN
RAD9A	controls-state-change-of	TP53
RAD1	controls-state-change-of	NBN
NBN	controls-state-change-of	DCLRE1C

cat co-occurred.sif
POLD4	interacts-with	RAD9A

```

**Comment by ozgunbabur** [comment]
Nice!

Alternative to ChiBE, you can go to [causalpath.cs.umb.edu](https://causalpath.cs.umb.edu), click on "Visualize results from previous analysis" and select the root folder of your analysis. Then double-click on a sif file on the left. This is an unrelated tool but it can visualize .sif with their corresponding .format just like ChiBE.

**Comment by john-alexander** [comment]
Ok that dint seem to work - but cytoscape worked though

**Comment by ozgunbabur** [comment]
Do you mean the Cytoscape desktop app or the link that I gave you?

**Comment by john-alexander** [comment]
Cytoscape desktop app

**Comment by ozgunbabur** [comment]
Try [causalpath.cs.umb.edu](https://causalpath.cs.umb.edu/) as well. It adds the alteration rates in the visualization via color coding.

**Comment by ozgunbabur** [comment]
But you can visualize the result-groups.cus file only using ChiBE, which runs on Ubuntu. I took a run with 
```max-group-size = 5
first-level-random-iteration = 10000
data-file = Matrix_CNA_RNA__all_genes__mutex1.txt
search-on-signaling-network = true
score-cutoff = 0.02
minimum-alteration-count-threshold = 3
```
It finished in about 2 hours and generated these groups as visualized by ChiBE.

![result-groups](https://user-images.githubusercontent.com/1376779/191846975-e441347d-d9fe-4887-946a-8d917643030b.svg)

Also, don't forget to look in oncoprint.txt file as this gives you an idea about the shape of mutual exclusivity for each group.
