### ISSUE TITLE
running mutex on cell line data

### ISSUE THREAD

**Issue by Skumarerva** [PathwayAndDataAnalysis/mutex#14]
Hello, I ran mutex on a group of genes for cell line data. However when I run it , the message comes as there are zero number of mutex groups.  Moreover, I get only the ranked scores file as output and no fdr cut off file. Based on what I understood from the wiki , that one has to map the frd cut off to the scores in the ranked scores.  I am sending you a trial file
So does this mean there are no mutually exclusive groups. Apologize if these questions are too basic.
[Breast.txt](https://github.com/PathwayAndDataAnalysis/mutex/files/9940233/Breast.txt)
[parameters.txt]
![Capture_mutex](https://user-images.githubusercontent.com/19316250/200025872-a2fd3928-f687-45e7-9faf-4ef8f7114a22.JPG)
(https://github.com/PathwayAndDataAnalysis/mutex/files/9940234/parameters.txt)

**Comment by ozgunbabur** [comment]
Hi Shwetha,

Yes, there are no significant mutex groups in your case. In the top of the ranked-groups.txt file I see two groups with about 0.08 score, which is too high to be considered significant.
