### ISSUE TITLE
Mutex ask for user and password and .zip crashes

### ISSUE THREAD

**Issue by Tato14** [PathwayAndDataAnalysis/mutex#6]
Hi,

When I try to git clone Mutex using: `git clone https://github.com/PathwayAndDataAbalysis/mutex` it asks for user and password. Also, when I download the .zip from your page and tried to run the program, it crashes with the following message:
```
Exception in thread "main" java.lang.NullPointerException
    at org.cbio.mutex.Main.main(Main.java:125)
```

 Any idea what is happening?

Thanks!
J

**Comment by XiangweiZhai** [comment]
The author accidentally gave a wrong URL：https://github.com/PathwayAndDataAbalysis/mute. 
Maybe you should try to execute this line of code：git clone https://github.com/pathwayanddataanalysis/mutex.

**Comment by ozgunbabur** [comment]
Hi Joan, 

Yes, XiangweiZhai is right, there was a typo in the URL, fixed now. Thanks for writing here.

Where did you get the zip file? It probably needs to be updated.

Ozgun

**Comment by XiangweiZhai** [comment]
Hi ozgunbabur,
I downloaded it directly from your homepage last week. I am very interested in your work, but I am not familiar with java. I encountered some problems when running the program and posted these problems to the web page, please check it. Looking forward to your help.

**Comment by ozgunbabur** [comment]
Hi @XiangweiZhai,

Thanks for opening the issue. Please see my reply there.

In short, I could not get the error that you mentioned. One thing I am doing differently is that I am using Git to download the code, not the zip file that GitHub provides you. Please follow the instructions on the front page and let me know if you still get the same problem.
