### ISSUE TITLE
error in compiling

### ISSUE THREAD

**Issue by blueskypie** [PathwayAndDataAnalysis/mutex#8]
hi
I got the following error while running `mvn clean compile`

> [INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.949 s
[INFO] Finished at: 2020-10-28T13:34:32-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mutex: Could not resolve dependencies for project org.cbio:mutex:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: org.biopax.paxtools:paxtools-core:jar:5.1.0-SNAPSHOT, org.biopax.paxtools:paxtools-query:jar:5.1.0-SNAPSHOT, org.biopax.paxtools:pattern:jar:5.1.0-SNAPSHOT: Could not find artifact org.biopax.paxtools:paxtools-core:jar:5.1.0-SNAPSHOT in panda (https://raw.githubusercontent.com/PathwayAndDataAnalysis/repo/master/maven-repo/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I'm using Ubuntu 18.04, Apache Maven 3.6.0, Java version: 14.0.1.

Thanks!

**Comment by ozgunbabur** [comment]
Hi blueskypie,

Just changed versions of some resource libraries. It should see the required Paxtools libraries now. Can you please update and test again?

Thanks.

**Comment by blueskypie** [comment]
Yes, compiled successfully! Thank you!
